# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc import dataframe_pb2 as grpc_dot_dataframe__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/dataframe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataFrameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyAccountsParallel = channel.unary_unary(
                '/dataframe.DataFrameService/ClassifyAccountsParallel',
                request_serializer=grpc_dot_dataframe__pb2.ClassifyAccountsRequest.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.SummaryStats = channel.unary_unary(
                '/dataframe.DataFrameService/SummaryStats',
                request_serializer=grpc_dot_dataframe__pb2.SummaryStatsRequest.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.Top10CidadesTransacoes = channel.unary_unary(
                '/dataframe.DataFrameService/Top10CidadesTransacoes',
                request_serializer=grpc_dot_dataframe__pb2.Top10CidadesRequest.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.AbnormalTransactions = channel.unary_unary(
                '/dataframe.DataFrameService/AbnormalTransactions',
                request_serializer=grpc_dot_dataframe__pb2.AbnormalTransactionsRequest.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.AddTransaction = channel.unary_unary(
                '/dataframe.DataFrameService/AddTransaction',
                request_serializer=grpc_dot_dataframe__pb2.AddTransactionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddAccount = channel.unary_unary(
                '/dataframe.DataFrameService/AddAccount',
                request_serializer=grpc_dot_dataframe__pb2.AddAccountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class DataFrameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyAccountsParallel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummaryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Top10CidadesTransacoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbnormalTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTransaction(self, request, context):
        """Novas funções
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataFrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyAccountsParallel': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyAccountsParallel,
                    request_deserializer=grpc_dot_dataframe__pb2.ClassifyAccountsRequest.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.OperationResponse.SerializeToString,
            ),
            'SummaryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.SummaryStats,
                    request_deserializer=grpc_dot_dataframe__pb2.SummaryStatsRequest.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.OperationResponse.SerializeToString,
            ),
            'Top10CidadesTransacoes': grpc.unary_unary_rpc_method_handler(
                    servicer.Top10CidadesTransacoes,
                    request_deserializer=grpc_dot_dataframe__pb2.Top10CidadesRequest.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.OperationResponse.SerializeToString,
            ),
            'AbnormalTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.AbnormalTransactions,
                    request_deserializer=grpc_dot_dataframe__pb2.AbnormalTransactionsRequest.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.OperationResponse.SerializeToString,
            ),
            'AddTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTransaction,
                    request_deserializer=grpc_dot_dataframe__pb2.AddTransactionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAccount,
                    request_deserializer=grpc_dot_dataframe__pb2.AddAccountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataframe.DataFrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataframe.DataFrameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataFrameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyAccountsParallel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/ClassifyAccountsParallel',
            grpc_dot_dataframe__pb2.ClassifyAccountsRequest.SerializeToString,
            grpc_dot_dataframe__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummaryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/SummaryStats',
            grpc_dot_dataframe__pb2.SummaryStatsRequest.SerializeToString,
            grpc_dot_dataframe__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Top10CidadesTransacoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/Top10CidadesTransacoes',
            grpc_dot_dataframe__pb2.Top10CidadesRequest.SerializeToString,
            grpc_dot_dataframe__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbnormalTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/AbnormalTransactions',
            grpc_dot_dataframe__pb2.AbnormalTransactionsRequest.SerializeToString,
            grpc_dot_dataframe__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/AddTransaction',
            grpc_dot_dataframe__pb2.AddTransactionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataframe.DataFrameService/AddAccount',
            grpc_dot_dataframe__pb2.AddAccountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
