# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataframe.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    4,
    '',
    'dataframe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61taframe.proto\"Y\n\x07Summary\x12\x0c\n\x04mean\x18\x01 \x01(\x02\x12\x0b\n\x03min\x18\x02 \x01(\x02\x12\x0b\n\x03max\x18\x03 \x01(\x02\x12\n\n\x02q1\x18\x04 \x01(\x02\x12\x0e\n\x06median\x18\x05 \x01(\x02\x12\n\n\x02q3\x18\x06 \x01(\x02\"U\n\x0bTransaction\x12\x10\n\x08idSender\x18\x01 \x01(\x05\x12\x12\n\nidReceiver\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x10\n\x08location\x18\x04 \x01(\t\"\"\n\x08\x41\x62normal\x12\x16\n\x0evectorAbnormal\x18\x01 \x03(\x05\"\x0e\n\x0cGenericInput\"\x11\n\x0fGenericResponse\"\x1e\n\tAccountId\x12\x11\n\tidAccount\x18\x01 \x01(\x05\"\x1a\n\x05\x43lass\x12\x11\n\tclassName\x18\x01 \x01(\t\"\x1f\n\x10NumberOfAccounts\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\xf6\x01\n\x12ProcessingServices\x12\x30\n\x0e\x61\x64\x64Transaction\x12\x0c.Transaction\x1a\x10.GenericResponse\x12+\n\x10transactionsInfo\x12\r.GenericInput\x1a\x08.Summary\x12\x30\n\x14\x61\x62normalTransactions\x12\r.GenericInput\x1a\t.Abnormal\x12\"\n\x0c\x61\x63\x63ountClass\x12\n.AccountId\x1a\x06.Class\x12+\n\x0e\x61\x63\x63ountByClass\x12\x06.Class\x1a\x11.NumberOfAccountsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataframe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARY']._serialized_start=19
  _globals['_SUMMARY']._serialized_end=108
  _globals['_TRANSACTION']._serialized_start=110
  _globals['_TRANSACTION']._serialized_end=195
  _globals['_ABNORMAL']._serialized_start=197
  _globals['_ABNORMAL']._serialized_end=231
  _globals['_GENERICINPUT']._serialized_start=233
  _globals['_GENERICINPUT']._serialized_end=247
  _globals['_GENERICRESPONSE']._serialized_start=249
  _globals['_GENERICRESPONSE']._serialized_end=266
  _globals['_ACCOUNTID']._serialized_start=268
  _globals['_ACCOUNTID']._serialized_end=298
  _globals['_CLASS']._serialized_start=300
  _globals['_CLASS']._serialized_end=326
  _globals['_NUMBEROFACCOUNTS']._serialized_start=328
  _globals['_NUMBEROFACCOUNTS']._serialized_end=359
  _globals['_PROCESSINGSERVICES']._serialized_start=362
  _globals['_PROCESSINGSERVICES']._serialized_end=608
# @@protoc_insertion_point(module_scope)
