# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc import dataframe_pb2 as grpc_dot_dataframe__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/dataframe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessingServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTransaction = channel.unary_unary(
                '/processing.ProcessingServices/AddTransaction',
                request_serializer=grpc_dot_dataframe__pb2.Transaction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TransactionsInfo = channel.unary_unary(
                '/processing.ProcessingServices/TransactionsInfo',
                request_serializer=grpc_dot_dataframe__pb2.GenericInput.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.Summary.FromString,
                _registered_method=True)
        self.AbnormalTransactions = channel.unary_unary(
                '/processing.ProcessingServices/AbnormalTransactions',
                request_serializer=grpc_dot_dataframe__pb2.GenericInput.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.Abnormal.FromString,
                _registered_method=True)
        self.AccountClass = channel.unary_unary(
                '/processing.ProcessingServices/AccountClass',
                request_serializer=grpc_dot_dataframe__pb2.AccountId.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.Class.FromString,
                _registered_method=True)
        self.AccountByClass = channel.unary_unary(
                '/processing.ProcessingServices/AccountByClass',
                request_serializer=grpc_dot_dataframe__pb2.Class.SerializeToString,
                response_deserializer=grpc_dot_dataframe__pb2.NumberOfAccounts.FromString,
                _registered_method=True)


class ProcessingServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbnormalTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountByClass(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessingServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTransaction,
                    request_deserializer=grpc_dot_dataframe__pb2.Transaction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TransactionsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionsInfo,
                    request_deserializer=grpc_dot_dataframe__pb2.GenericInput.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.Summary.SerializeToString,
            ),
            'AbnormalTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.AbnormalTransactions,
                    request_deserializer=grpc_dot_dataframe__pb2.GenericInput.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.Abnormal.SerializeToString,
            ),
            'AccountClass': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountClass,
                    request_deserializer=grpc_dot_dataframe__pb2.AccountId.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.Class.SerializeToString,
            ),
            'AccountByClass': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountByClass,
                    request_deserializer=grpc_dot_dataframe__pb2.Class.FromString,
                    response_serializer=grpc_dot_dataframe__pb2.NumberOfAccounts.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'processing.ProcessingServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('processing.ProcessingServices', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessingServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processing.ProcessingServices/AddTransaction',
            grpc_dot_dataframe__pb2.Transaction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processing.ProcessingServices/TransactionsInfo',
            grpc_dot_dataframe__pb2.GenericInput.SerializeToString,
            grpc_dot_dataframe__pb2.Summary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbnormalTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processing.ProcessingServices/AbnormalTransactions',
            grpc_dot_dataframe__pb2.GenericInput.SerializeToString,
            grpc_dot_dataframe__pb2.Abnormal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processing.ProcessingServices/AccountClass',
            grpc_dot_dataframe__pb2.AccountId.SerializeToString,
            grpc_dot_dataframe__pb2.Class.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountByClass(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/processing.ProcessingServices/AccountByClass',
            grpc_dot_dataframe__pb2.Class.SerializeToString,
            grpc_dot_dataframe__pb2.NumberOfAccounts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
