# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/dataframe.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc/dataframe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14grpc/dataframe.proto\x12\nprocessing\x1a\x1bgoogle/protobuf/empty.proto\"\x0e\n\x0cGenericInput\"U\n\x0bTransaction\x12\x10\n\x08idSender\x18\x01 \x01(\x05\x12\x12\n\nidReceiver\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x10\n\x08location\x18\x04 \x01(\t\"Y\n\x07Summary\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\n\n\x02q1\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\n\n\x02q3\x18\x04 \x01(\x02\x12\x0b\n\x03max\x18\x05 \x01(\x02\x12\x0c\n\x04mean\x18\x06 \x01(\x02\"\"\n\x08\x41\x62normal\x12\x16\n\x0evectorAbnormal\x18\x01 \x03(\x05\"\x1e\n\tAccountId\x12\x11\n\tidAccount\x18\x01 \x01(\x05\"\x1a\n\x05\x43lass\x12\x11\n\tclassName\x18\x01 \x01(\t\"\x1f\n\x10NumberOfAccounts\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\xdf\x02\n\x12ProcessingServices\x12\x41\n\x0e\x41\x64\x64Transaction\x12\x17.processing.Transaction\x1a\x16.google.protobuf.Empty\x12\x41\n\x10TransactionsInfo\x12\x18.processing.GenericInput\x1a\x13.processing.Summary\x12\x46\n\x14\x41\x62normalTransactions\x12\x18.processing.GenericInput\x1a\x14.processing.Abnormal\x12\x38\n\x0c\x41\x63\x63ountClass\x12\x15.processing.AccountId\x1a\x11.processing.Class\x12\x41\n\x0e\x41\x63\x63ountByClass\x12\x11.processing.Class\x1a\x1c.processing.NumberOfAccountsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.dataframe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERICINPUT']._serialized_start=65
  _globals['_GENERICINPUT']._serialized_end=79
  _globals['_TRANSACTION']._serialized_start=81
  _globals['_TRANSACTION']._serialized_end=166
  _globals['_SUMMARY']._serialized_start=168
  _globals['_SUMMARY']._serialized_end=257
  _globals['_ABNORMAL']._serialized_start=259
  _globals['_ABNORMAL']._serialized_end=293
  _globals['_ACCOUNTID']._serialized_start=295
  _globals['_ACCOUNTID']._serialized_end=325
  _globals['_CLASS']._serialized_start=327
  _globals['_CLASS']._serialized_end=353
  _globals['_NUMBEROFACCOUNTS']._serialized_start=355
  _globals['_NUMBEROFACCOUNTS']._serialized_end=386
  _globals['_PROCESSINGSERVICES']._serialized_start=389
  _globals['_PROCESSINGSERVICES']._serialized_end=740
# @@protoc_insertion_point(module_scope)
